// lib/industriasData.js
export const INDUSTRIAS_DETALLE = {
  estetica: {
    slug: 'estetica',
    nombre: 'Centro de Estética',
    emoji: '💅',
    img: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=120&h=120&fit=crop&crop=faces,center&q=90',
    color: '#FF6B00',
    colorBg: 'rgba(255,107,0,0.08)',
    colorBorder: 'rgba(255,107,0,0.25)',
    tagline: 'Tu centro lleno, cero citas perdidas',
    descripcion: 'Agente IA que gestiona citas de facial, depilación y tratamientos mientras tú trabajas con las manos ocupadas. Atiende WhatsApp y llamadas 24/7 sincronizando todo con tu calendario.',
    heroStats: [
      { valor: '-65%', label: 'menos no-shows' },
      { valor: '24/7', label: 'atención automática' },
      { valor: '+38%', label: 'citas recuperadas' },
    ],
    funciones: [
      { icon: '📞', titulo: 'Cero llamadas perdidas', desc: 'El agente de voz atiende cada llamada que entra aunque estés en cabina. Agenda, informa y cobra señales.' },
      { icon: '💬', titulo: 'WhatsApp 24/7', desc: 'Responde mensajes, envía menú de servicios, confirma citas y cobra anticipos sin que toques el teléfono.' },
      { icon: '📅', titulo: 'Agenda sincronizada', desc: 'Conectada a Google Calendar o Supabase. Sin dobles reservas, sin huecos muertos.' },
      { icon: '🔔', titulo: 'Recordatorios automáticos', desc: 'El sistema avisa a tus clientes 24h y 1h antes. Los no-shows caen más del 60%.' },
      { icon: '💳', titulo: 'Cobro de señales', desc: 'Solicita pago de señal para confirmar la cita. Integrado con Stripe y Bizum.' },
      { icon: '📊', titulo: 'Panel de control', desc: 'Ve ocupación, ingresos y clientes recurrentes en tiempo real desde el móvil.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, quiero pedir cita para limpieza facial' },
      { rol: 'agente', texto: '¡Hola! Con mucho gusto 😊 La limpieza facial profunda tiene un valor de 45€ y una duración de 60 minutos. ¿Qué día te vendría mejor?' },
      { rol: 'cliente', texto: '¿Tenéis disponibilidad el jueves por la tarde?' },
      { rol: 'agente', texto: '¡Sí! El jueves tenemos disponible: 16:00h, 17:30h y 19:00h. ¿Cuál prefieres? ✨' },
      { rol: 'cliente', texto: 'Las 17:30 perfecto, soy Laura' },
      { rol: 'agente', texto: '✅ ¡Laura, tu cita de limpieza facial está confirmada para el jueves a las 17:30h! Para asegurar tu plaza, te pediré una señal de 10€ por Bizum al 6XX XXX XXX. Te mando recordatorio el día anterior 📲' },
    ],
    casos: [
      { nombre: 'Centro Estético Áurea — Madrid', resultado: 'Recuperó más de 1.400€ en el primer mes con citas antes perdidas' },
      { nombre: 'Estética Luminosa — Barcelona', resultado: 'Los no-shows bajaron un 65% en 6 semanas' },
      { nombre: 'Centro Belleza Plena — Valencia', resultado: 'Llena la agenda completa cada semana sin contestar más llamadas' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'pro',
  },

  spa: {
    slug: 'spa',
    nombre: 'Spa & Masajes',
    emoji: '🛀',
    img: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#8B5CF6',
    colorBg: 'rgba(139,92,246,0.08)',
    colorBorder: 'rgba(139,92,246,0.25)',
    tagline: 'Reservas instantáneas para cada cabina',
    descripcion: 'Agenda inteligente para múltiples cabinas y terapeutas. El cliente reserva en WhatsApp en menos de 30 segundos, elige terapeuta y tipo de masaje, y recibe confirmación automática.',
    heroStats: [
      { valor: '< 30s', label: 'para reservar' },
      { valor: '100%', label: 'ocupación de cabinas' },
      { valor: '-70%', label: 'no-shows' },
    ],
    funciones: [
      { icon: '📅', titulo: 'Gestión multiterapia', desc: 'El agente gestiona la agenda de todas tus cabinas y terapeutas sin conflictos ni huecos.' },
      { icon: '💬', titulo: 'Reserva por WhatsApp en 30 segundos', desc: 'El cliente elige tratamiento, terapeuta y horario en una conversación natural. Sin llamadas, sin esperas.' },
      { icon: '💳', titulo: 'Cobro de señal anticipada', desc: 'Confirma la reserva con un pago parcial. Reduce cancelaciones de última hora drásticamente.' },
      { icon: '🔔', titulo: 'Recordatorios personalizados', desc: 'Mensaje el día anterior y 2 horas antes con preparación recomendada según el tratamiento.' },
      { icon: '⭐', titulo: 'Solicitud de reseñas', desc: 'Tras cada sesión, el agente pide valoración en Google automáticamente.' },
      { icon: '🎁', titulo: 'Bonos regalo automáticos', desc: 'Vende bonos regalo por WhatsApp, genera el código y lo envía al comprador al instante.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, ¿hacéis masaje con piedras calientes?' },
      { rol: 'agente', texto: '¡Hola! Sí, tenemos masaje con piedras calientes de 75 minutos por 65€. Es perfecto para liberar la tensión muscular profunda 😌 ¿Quieres reservar?' },
      { rol: 'cliente', texto: 'Sí, ¿tenéis disponibilidad este sábado?' },
      { rol: 'agente', texto: 'El sábado tenemos estos horarios disponibles:\n\n⏰ 10:00h con Elena\n⏰ 12:30h con Marta\n⏰ 17:00h con Elena\n\n¿Alguno te viene bien?' },
      { rol: 'cliente', texto: 'Las 12:30 con Marta' },
      { rol: 'agente', texto: '✅ Reserva confirmada: sábado 12:30h con Marta, masaje piedras calientes. Para asegurar tu plaza necesito una señal de 15€ por Bizum al 6XX XXX XXX 🙏' },
    ],
    casos: [
      { nombre: 'Spa Esencia — Barcelona', resultado: 'Cabinas al 100% de ocupación los fines de semana' },
      { nombre: 'Relax & Zen — Madrid', resultado: 'Vendió 42 bonos regalo en el primer mes sin esfuerzo' },
      { nombre: 'Centro Wellness — Sevilla', resultado: 'Eliminó el 80% de cancelaciones con cobro de señal' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'pro',
  },

  dental: {
    slug: 'dental',
    nombre: 'Clínica Dental',
    emoji: '🦷',
    img: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#14B8A6',
    colorBg: 'rgba(20,184,166,0.08)',
    colorBorder: 'rgba(20,184,166,0.25)',
    tagline: 'Pacientes puntuales, consulta sin huecos',
    descripcion: 'Confirmaciones automáticas, recaptación de pacientes inactivos y gestión de urgencias con IA de voz. Tu recepcionista virtual que nunca falta.',
    heroStats: [
      { valor: '-60%', label: 'inasistencias' },
      { valor: '3x', label: 'pacientes recaptados' },
      { valor: '24/7', label: 'atención urgencias' },
    ],
    funciones: [
      { icon: '📅', titulo: 'Agenda dental inteligente', desc: 'Gestiona la agenda de todos los dentistas y especialidades sin conflictos. El paciente agenda en segundos.' },
      { icon: '🔔', titulo: 'Recordatorios y confirmaciones', desc: 'El agente pide confirmación 48h antes. Si no confirma, libera el hueco y avisa a la lista de espera.' },
      { icon: '🚑', titulo: 'Gestión de urgencias', desc: 'El agente de voz atiende llamadas de urgencia fuera de horario, evalúa el caso y agenda para el día siguiente.' },
      { icon: '🔄', titulo: 'Recaptación automática', desc: '"Hola María, llevas 8 meses sin venir. ¿Agendamos tu revisión anual?" — enviado automáticamente.' },
      { icon: '📱', titulo: 'Presupuestos por WhatsApp', desc: 'El paciente recibe el presupuesto detallado con opciones de pago fraccionado directamente en su móvil.' },
      { icon: '⭐', titulo: 'Encuestas de satisfacción', desc: 'Tras cada visita, el agente pide valoración y reseña en Google para mejorar tu reputación online.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, quiero pedir cita para una limpieza dental' },
      { rol: 'agente', texto: '¡Hola! La limpieza dental básica tiene un coste de 60€ e incluye revisión completa. ¿Te vendría esta semana o prefieres la próxima? 🙂' },
      { rol: 'cliente', texto: '¿Tenéis el viernes por la mañana?' },
      { rol: 'agente', texto: 'El viernes tenemos disponible con la Dra. Gómez:\n\n⏰ 9:00h\n⏰ 10:30h\n⏰ 11:30h\n\n¿Cuál prefieres?' },
      { rol: 'cliente', texto: '9am perfecto' },
      { rol: 'agente', texto: '✅ Cita confirmada: viernes 9:00h con la Dra. Gómez, limpieza dental. Te recordaré el jueves por la tarde. ¿Tienes alguna alergia o medicación que debamos saber? 🦷' },
    ],
    casos: [
      { nombre: 'Clínica Dental Blanca — Madrid', resultado: 'Redujo huecos vacíos de 8 a 1 por semana' },
      { nombre: 'Odontología Avanzada — Valencia', resultado: 'Recaptó 180 pacientes inactivos en 30 días' },
      { nombre: 'Sonrisas Clinic — Barcelona', resultado: 'Reseñas Google pasaron de 42 a 210 en 3 meses' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'pro',
  },

  'medicina-estetica': {
    slug: 'medicina-estetica',
    nombre: 'Medicina Estética',
    emoji: '💉',
    img: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#3B82F6',
    colorBg: 'rgba(59,130,246,0.08)',
    colorBorder: 'rgba(59,130,246,0.25)',
    tagline: 'Filtra, agenda y fideliza pacientes con IA',
    descripcion: 'Filtrado de pacientes, consentimientos digitales y seguimiento post-tratamiento automatizado. Gestiona botóx, ácido hialurónico, láser y más sin saturar tu consulta.',
    heroStats: [
      { valor: '5x', label: 'leads cualificados' },
      { valor: '-80%', label: 'tiempo en consultas informativas' },
      { valor: '+45%', label: 'pacientes recurrentes' },
    ],
    funciones: [
      { icon: '🔍', titulo: 'Filtrado inteligente de pacientes', desc: 'El agente pre-cualifica: qué tratamiento busca, si tiene contraindicaciones y si es candidato. Tu médico solo ve pacientes aptos.' },
      { icon: '📄', titulo: 'Consentimientos digitales', desc: 'Envía, gestiona y almacena consentimientos informados firmados digitalmente antes de la cita.' },
      { icon: '💬', titulo: 'Consulta informativa por WhatsApp', desc: 'Responde preguntas sobre tratamientos, precios, duración y postoperatorio sin que el médico intervenga.' },
      { icon: '🔔', titulo: 'Seguimiento post-tratamiento', desc: '"¿Cómo te encuentras a las 48h del tratamiento?" — El agente hace seguimiento y detecta incidencias a tiempo.' },
      { icon: '🗓️', titulo: 'Agenda de mantenimientos', desc: 'Recuerda automáticamente cuándo toca la sesión de mantenimiento según el protocolo de cada tratamiento.' },
      { icon: '📊', titulo: 'CRM de pacientes estéticos', desc: 'Historial de tratamientos, fotos antes/después, preferencias y seguimiento de resultados en un solo lugar.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, me interesa información sobre el botóx' },
      { rol: 'agente', texto: '¡Hola! Encantada de informarte 😊 El bótox es un tratamiento preventivo y corrector para arrugas de expresión. Dura entre 4 y 6 meses. ¿Qué zona te preocupa más? (entrecejo, frente, patas de gallo...)' },
      { rol: 'cliente', texto: 'El entrecejo principalmente, ¿cuánto cuesta?' },
      { rol: 'agente', texto: 'El tratamiento de entrecejo tiene un coste desde 180€. Incluye consulta previa con la Dra. Martínez y revisión a las 2 semanas.\n\nAntes de agendar, ¿tienes alguna de estas condiciones? (embarazo, lactancia, alergia a proteínas bótulo...)' },
      { rol: 'cliente', texto: 'No tengo ninguna de esas, quiero pedir cita' },
      { rol: 'agente', texto: '✅ Perfecto, eres candidata ideal. Esta semana tenemos disponible el miércoles a las 11h o el viernes a las 17h. ¿Cuál prefieres? Te enviaré el consentimiento informado por adelantado 📄' },
    ],
    casos: [
      { nombre: 'Clínica Estética Renové — Madrid', resultado: 'Redujo consultas informativas gratuitas en un 75%' },
      { nombre: 'Med Aesthetic — Barcelona', resultado: 'Aumentó repeticiones de tratamiento un 45% con seguimiento IA' },
      { nombre: 'Dra. Pérez Clinic — Sevilla', resultado: 'Eliminó no-shows con cobro de señal automático' },
    ],
    planes: ['Pro', 'Enterprise'],
    planRecomendado: 'pro',
  },

  taller: {
    slug: 'taller',
    nombre: 'Talleres & Mecánica',
    emoji: '🔧',
    img: 'https://images.unsplash.com/photo-1530046339160-ce3e530c7d2f?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#FF6B6B',
    colorBg: 'rgba(255,107,107,0.08)',
    colorBorder: 'rgba(255,107,107,0.2)',
    tagline: 'Tu taller en piloto automático',
    descripcion: 'Automatiza citas, presupuestos y seguimiento de vehículos. Tu agente IA atiende clientes por WhatsApp las 24 horas, agenda revisiones y envía recordatorios automáticos.',
    heroStats: [
      { valor: '3x', label: 'Más citas agendadas' },
      { valor: '80%', label: 'Menos llamadas perdidas' },
      { valor: '24/7', label: 'Atención continua' },
    ],
    funciones: [
      { icon: '📅', titulo: 'Agendamiento automático de citas', desc: 'Tu agente recibe solicitudes por WhatsApp, consulta disponibilidad y agenda la cita sin que intervengas.' },
      { icon: '🚗', titulo: 'Historial de vehículos', desc: 'Registra automáticamente cada vehículo: matrícula, modelo, año, servicios realizados y próximo mantenimiento.' },
      { icon: '💰', titulo: 'Presupuestos automáticos', desc: 'El agente genera cotizaciones preliminares basadas en la descripción del problema. Envía al cliente y espera aprobación.' },
      { icon: '🔔', titulo: 'Recordatorios de mantenimiento', desc: '"Tu vehículo necesita revisión de aceite en 500 km." Fideliza clientes sin esfuerzo.' },
      { icon: '💬', titulo: 'Seguimiento de reparaciones', desc: 'Notifica al cliente el estado de su vehículo: recibido, en diagnóstico, en reparación, listo para recoger.' },
      { icon: '⭐', titulo: 'Reseñas automáticas', desc: 'Al terminar el servicio, el agente pide reseña en Google y guarda feedback en tu CRM.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, necesito cambio de aceite para mi Seat Ibiza 2020' },
      { rol: 'agente', texto: '¡Hola! Con gusto te ayudo 👋 El cambio de aceite para tu Seat Ibiza 2020 tiene un valor aproximado de 65€ e incluye filtro. ¿Te gustaría agendar una cita?' },
      { rol: 'cliente', texto: 'Sí, ¿tienen disponibilidad mañana?' },
      { rol: 'agente', texto: 'Claro, mañana tenemos disponible: 8:00am, 10:30am y 2:00pm. ¿Cuál prefieres? 😊' },
      { rol: 'cliente', texto: '10:30am perfecto' },
      { rol: 'agente', texto: '✅ ¡Listo! Cita confirmada para mañana a las 10:30am. Te enviaré un recordatorio 1 hora antes. ¿Cuál es la matrícula del vehículo?' },
    ],
    casos: [
      { nombre: 'AutoCenter — Madrid', resultado: 'Pasó de 8 a 23 citas semanales en el primer mes' },
      { nombre: 'Taller Don Pedro — Sevilla', resultado: 'Redujo llamadas perdidas en un 85%' },
      { nombre: 'Mecánica Express — Barcelona', resultado: 'Recuperó 40 clientes inactivos con recordatorios IA' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'pro',
  },

  peluqueria: {
    slug: 'peluqueria',
    nombre: 'Peluquerías & Spa',
    emoji: '✂️',
    img: 'https://images.unsplash.com/photo-1560066984-138daaa5f571?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#EC4899',
    colorBg: 'rgba(236,72,153,0.08)',
    colorBorder: 'rgba(236,72,153,0.2)',
    tagline: 'Tu agenda llena, tú enfocada en crear',
    descripcion: 'Olvídate de responder mensajes todo el día. Tu agente IA gestiona reservas, confirma citas, recuerda a los clientes y fideliza tu base con mensajes personalizados.',
    heroStats: [
      { valor: '4h', label: 'Ahorradas por día' },
      { valor: '95%', label: 'Tasa de confirmación' },
      { valor: '2x', label: 'Más reseñas Google' },
    ],
    funciones: [
      { icon: '📅', titulo: 'Reservas 24/7 por WhatsApp', desc: 'Tus clientes reservan a cualquier hora. El agente conoce tu agenda y nunca doble-agenda.' },
      { icon: '💆', titulo: 'Catálogo de servicios con precios', desc: 'El agente informa precios, duración y disponibilidad: corte, color, keratina, manicure, masajes.' },
      { icon: '🔔', titulo: 'Recordatorios automáticos', desc: 'WhatsApp automático 24h y 1h antes de la cita. Reduce las no-shows hasta un 70%.' },
      { icon: '🎂', titulo: 'Fidelización de clientes', desc: 'El sistema recuerda cumpleaños y envía descuentos especiales automáticamente a tus clientes frecuentes.' },
      { icon: '📸', titulo: 'Portafolio digital', desc: 'Integra tu Instagram al agente para que los clientes vean tu trabajo antes de reservar.' },
      { icon: '💳', titulo: 'Gestión de pagos', desc: 'Informa métodos de pago, genera links de pago y registra transacciones en tu CRM.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Buenas, ¿cuánto vale el balayage?' },
      { rol: 'agente', texto: '¡Hola! El balayage tiene un valor desde 120€ dependiendo del largo y el efecto. ⏱️ Dura aproximadamente 3 horas. ¿Te gustaría ver ejemplos de nuestro trabajo?' },
      { rol: 'cliente', texto: 'Sí por favor, y también quiero saber disponibilidad para el sábado' },
      { rol: 'agente', texto: 'Aquí te dejo nuestro Instagram con trabajos recientes 👉 @estudio_elegance\n\nPara el sábado tenemos: 9:00am, 11:00am y 1:00pm disponibles. ¿Cuál te queda mejor? 💇‍♀️' },
      { rol: 'cliente', texto: '11am porfa, soy Patricia' },
      { rol: 'agente', texto: '✅ ¡Patricia, tu cita de balayage está confirmada para el sábado a las 11am! Te recuerdo el viernes. ¿Tienes alguna pregunta sobre el cuidado previo?' },
    ],
    casos: [
      { nombre: 'Studio Glam — Madrid', resultado: 'Llena el 100% de la agenda cada semana sin esfuerzo' },
      { nombre: 'Spa Natura — Valencia', resultado: 'Aumentó ventas de tratamientos premium en 60%' },
      { nombre: 'Peluquería Vogue — Sevilla', resultado: 'Eliminó por completo las citas no atendidas' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'starter',
  },

  inmobiliaria: {
    slug: 'inmobiliaria',
    nombre: 'Inmobiliarias',
    emoji: '🏠',
    img: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#3B82F6',
    colorBg: 'rgba(59,130,246,0.08)',
    colorBorder: 'rgba(59,130,246,0.2)',
    tagline: 'Tu agente inmobiliario que nunca descansa',
    descripcion: 'Filtra prospectos automáticamente, muestra propiedades, responde preguntas técnicas y agenda visitas. Tus asesores solo atienden clientes listos para comprar o alquilar.',
    heroStats: [
      { valor: '5x', label: 'Más leads calificados' },
      { valor: '60%', label: 'Menos tiempo en filtrado' },
      { valor: '24/7', label: 'Atención de prospectos' },
    ],
    funciones: [
      { icon: '🏘️', titulo: 'Catálogo de propiedades inteligente', desc: 'El agente pregunta: presupuesto, zona, habitaciones y tipo. Filtra y muestra solo las propiedades que encajan.' },
      { icon: '📋', titulo: 'Calificación automática de leads', desc: 'Clasifica prospectos por nivel de urgencia, capacidad económica e intención de compra.' },
      { icon: '📅', titulo: 'Agenda de visitas automática', desc: 'El agente coordina visitas, confirma al prospecto y al asesor, y envía la dirección automáticamente.' },
      { icon: '📊', titulo: 'Seguimiento post-visita', desc: 'Después de cada visita: ¿qué te pareció? ¿tienes preguntas? ¿quieres hacer oferta?' },
      { icon: '📄', titulo: 'Información técnica de inmuebles', desc: 'Zona, área, precio, comunidad, garaje, planta, antigüedad. El agente responde todo sin que el asesor intervenga.' },
      { icon: '🔔', titulo: 'Alertas de nuevas propiedades', desc: 'Notifica automáticamente a prospectos cuando entra una propiedad que coincide con su búsqueda.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, busco piso en alquiler en Madrid, máximo 1.500€' },
      { rol: 'agente', texto: '¡Hola! Perfecto, tengo varias opciones en Madrid dentro de tu presupuesto 🏠\n\n¿Cuántas habitaciones necesitas y en qué zona prefieres?' },
      { rol: 'cliente', texto: '2 habitaciones, de preferencia en Chamberí o Malasaña' },
      { rol: 'agente', texto: 'Excelente elección! Tengo 3 opciones disponibles:\n\n🏠 Piso Chamberí - 2 hab, 2 baños, 1.400€/mes, 4ª planta\n🏠 Piso Malasaña - 2 hab, 1 baño, 1.250€/mes, garaje\n🏠 Piso Centro - 2 hab, 2 baños, 1.480€/mes, vistas despejadas\n\n¿Cuál te llama más la atención?' },
      { rol: 'cliente', texto: 'El de Chamberí, ¿podemos ver el fin de semana?' },
      { rol: 'agente', texto: '✅ ¡Claro! El sábado tenemos disponible 10am o 3pm. ¿Cuál prefieres? Te confirmo con el asesor de inmediato 📅' },
    ],
    casos: [
      { nombre: 'Inmobiliaria Atlántica — Madrid', resultado: 'Triplicó visitas agendadas en el primer mes' },
      { nombre: 'Propiedades del Mediterráneo', resultado: 'Redujo tiempo de calificación de leads de 2 días a 2 minutos' },
      { nombre: 'Inmobiliaria Levante — Valencia', resultado: 'Vendió 8 inmuebles en 45 días con leads del agente IA' },
    ],
    planes: ['Pro', 'Enterprise'],
    planRecomendado: 'pro',
  },

  restaurante: {
    slug: 'restaurante',
    nombre: 'Restaurantes & Comidas',
    emoji: '🍕',
    img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#EAB308',
    colorBg: 'rgba(234,179,8,0.08)',
    colorBorder: 'rgba(234,179,8,0.2)',
    tagline: 'Más pedidos, menos llamadas',
    descripcion: 'Tu restaurante toma pedidos por WhatsApp automáticamente, gestiona reservas de mesas, informa el menú del día y hace seguimiento de repartos sin que muevas un dedo.',
    heroStats: [
      { valor: '35%', label: 'Más pedidos por WhatsApp' },
      { valor: '0', label: 'Llamadas perdidas' },
      { valor: '2 seg', label: 'Tiempo de respuesta' },
    ],
    funciones: [
      { icon: '🍽️', titulo: 'Toma de pedidos por WhatsApp', desc: 'El agente muestra el menú, toma el pedido, confirma la dirección y el método de pago. Sin intervención humana.' },
      { icon: '📋', titulo: 'Menú digital interactivo', desc: 'Menú siempre actualizado con fotos, precios, ingredientes y alérgenos. Se actualiza en minutos desde el panel.' },
      { icon: '🪑', titulo: 'Reservas de mesas', desc: 'Gestiona reservas para grupos, eventos especiales y fechas importantes con confirmación automática.' },
      { icon: '🛵', titulo: 'Seguimiento de repartos', desc: 'Notifica al cliente cuando su pedido está en preparación, listo y en camino.' },
      { icon: '⏰', titulo: 'Tiempo de espera en tiempo real', desc: 'El agente informa tiempos de espera estimados según el volumen actual de pedidos.' },
      { icon: '🎉', titulo: 'Promociones automáticas', desc: 'Envía promos del día, combos especiales y descuentos a clientes frecuentes automáticamente.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola quiero pedir a domicilio' },
      { rol: 'agente', texto: '¡Hola! 🍕 Bienvenido a Pizza Express. ¿Ya conoces nuestro menú o quieres verlo?' },
      { rol: 'cliente', texto: 'Sí, una pizza familiar de pepperoni y una bebida' },
      { rol: 'agente', texto: '¡Perfecto! Tu pedido:\n🍕 Pizza familiar pepperoni - 14€\n🥤 Refresco 1.5L - 2,50€\n\nTotal: 16,50€\n\n¿Cuál es tu dirección de entrega? 📍' },
      { rol: 'cliente', texto: 'Calle Mayor 15, piso 3B, Madrid' },
      { rol: 'agente', texto: '✅ Pedido confirmado! Tiempo estimado: 35-40 minutos.\n\n¿Pagas en efectivo o por Bizum/tarjeta? 💳' },
    ],
    casos: [
      { nombre: 'Pizza Express — Madrid', resultado: 'Aumentó pedidos WhatsApp de 20 a 85 por día' },
      { nombre: 'Restaurante La Cazuela — Sevilla', resultado: 'Eliminó el 90% de llamadas telefónicas en hora pico' },
      { nombre: 'Sushi Delivery — Barcelona', resultado: 'Incrementó ticket promedio 25% con sugerencias IA' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'starter',
  },

  tienda: {
    slug: 'tienda',
    nombre: 'Tiendas & Retail',
    emoji: '🛒',
    img: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#10B981',
    colorBg: 'rgba(16,185,129,0.08)',
    colorBorder: 'rgba(16,185,129,0.2)',
    tagline: 'Tu vendedor digital que nunca cierra',
    descripcion: 'Tu tienda vende las 24 horas sin contratar más personal. El agente IA muestra productos, verifica disponibilidad, procesa pedidos y hace seguimiento postventa automáticamente.',
    heroStats: [
      { valor: '24/7', label: 'Ventas activas' },
      { valor: '40%', label: 'Más conversiones' },
      { valor: '3x', label: 'Más clientes atendidos' },
    ],
    funciones: [
      { icon: '🛍️', titulo: 'Catálogo digital con búsqueda inteligente', desc: 'El cliente describe lo que busca y el agente encuentra el producto exacto entre todo tu inventario.' },
      { icon: '📦', titulo: 'Verificación de inventario en tiempo real', desc: 'El agente consulta stock antes de confirmar. Si no hay, ofrece alternativas similares automáticamente.' },
      { icon: '💰', titulo: 'Asistente de ventas con upselling', desc: 'Sugiere productos complementarios: "Con esa impresora también llevas cartuchos de larga duración".' },
      { icon: '🚚', titulo: 'Gestión de pedidos y entregas', desc: 'Registra pedidos, coordina envíos y notifica al cliente el estado de su compra.' },
      { icon: '🔄', titulo: 'Postventa automático', desc: '¿Llegó bien? ¿necesitas factura? ¿quieres dejar una reseña? — automatizado.' },
      { icon: '📊', titulo: 'Reportes de productos más vendidos', desc: 'Tu panel muestra qué productos se consultan más y cuáles necesitan restock.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Buenas, ¿tienen cartuchos para impresora HP Deskjet 2775?' },
      { rol: 'agente', texto: '¡Hola! Sí, tenemos cartuchos para tu HP Deskjet 2775 🖨️\n\n✅ Cartucho negro HP 664 - 18€ (en stock)\n✅ Cartucho color HP 664 - 22€ (en stock)\n✅ Pack combo negro+color - 36€ (ahorras 4€)\n\n¿Cuál prefieres?' },
      { rol: 'cliente', texto: 'El combo, ¿hacéis envío a domicilio?' },
      { rol: 'agente', texto: '¡Claro! Envío disponible. ¿Cuál es tu dirección para calcular el coste? 📍\n\nTambién puedes recogerlo hoy en tienda, estamos abiertos hasta las 20h.' },
    ],
    casos: [
      { nombre: 'Papelería Central — Madrid', resultado: 'Atendió 3x más clientes con el mismo personal' },
      { nombre: 'Ferretería Los Andes — Barcelona', resultado: 'Ventas online crecieron 150% en 60 días' },
      { nombre: 'Distribuidora TecnoPlus — Bilbao', resultado: 'Redujo tiempo de atención por cliente de 8 min a 90 seg' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'pro',
  },

  papeleria: {
    slug: 'papeleria',
    nombre: 'Papelerías & Servicios',
    emoji: '📋',
    img: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#8B5CF6',
    colorBg: 'rgba(139,92,246,0.08)',
    colorBorder: 'rgba(139,92,246,0.2)',
    tagline: 'Cotizaciones instantáneas, clientes satisfechos',
    descripcion: 'Genera cotizaciones automáticas de impresión, diseño y servicios en segundos. Tu agente IA atiende solicitudes, hace seguimiento de pedidos y fideliza clientes recurrentes.',
    heroStats: [
      { valor: '10 seg', label: 'Cotización automática' },
      { valor: '70%', label: 'Menos tiempo en atención' },
      { valor: '2x', label: 'Más pedidos por WhatsApp' },
    ],
    funciones: [
      { icon: '💰', titulo: 'Cotizaciones automáticas de impresión', desc: 'El cliente indica qué necesita y el agente calcula y envía la cotización en segundos.' },
      { icon: '🎨', titulo: 'Solicitud de diseño gráfico', desc: 'Recibe briefings de diseño, confirma el encargo y hace seguimiento hasta la entrega.' },
      { icon: '📂', titulo: 'Gestión de pedidos', desc: 'Registra cada pedido, asigna número de seguimiento y notifica cuando está listo.' },
      { icon: '🖨️', titulo: 'Catálogo de servicios con precios', desc: 'Impresión, plastificado, encuadernación, copias, ploteos, tarjetas de presentación.' },
      { icon: '🔔', titulo: 'Avisos de pedido listo', desc: '"Tu pedido de 200 folletos ya está listo para recoger" — automático, sin que hagas nada.' },
      { icon: '📊', titulo: 'Clientes frecuentes con descuentos', desc: 'El sistema aplica descuentos automáticos según el historial de compras del cliente.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Buenas, necesito 500 folletos a color tamaño A4 para un evento' },
      { rol: 'agente', texto: '¡Hola! Para 500 folletos a color tamaño A4:\n\n📄 Papel bond 90g: 55€\n📄 Papel couché brillante: 75€\n📄 Papel couché mate: 72€\n\n⏱️ Tiempo de entrega: 2-3 horas\n\n¿Tienes el diseño listo o necesitas que lo hagamos? 🎨' },
      { rol: 'cliente', texto: 'Ya tengo el diseño, lo envío ahora. ¿Cuándo estarían listos?' },
      { rol: 'agente', texto: '¡Perfecto! Envía el archivo en PDF o AI a este mismo chat. Si lo pides antes de las 11am, lo tienes listo hoy por la tarde. ¿Confirmas en papel couché brillante? 🖨️' },
    ],
    casos: [
      { nombre: 'Copy Rápido — Madrid', resultado: 'Cotizaciones automáticas ahorraron 4 horas diarias' },
      { nombre: 'Papelería Universitaria — Salamanca', resultado: 'Atendió 5x más clientes en temporada escolar' },
      { nombre: 'Servicios Gráficos Sur — Málaga', resultado: 'Cero pedidos perdidos por falta de atención' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'starter',
  },

  gimnasio: {
    slug: 'gimnasio',
    nombre: 'Gimnasios & Fitness',
    emoji: '🏋️',
    img: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#F97316',
    colorBg: 'rgba(249,115,22,0.08)',
    colorBorder: 'rgba(249,115,22,0.2)',
    tagline: 'Más miembros, menos gestión',
    descripcion: 'Tu gimnasio gestiona inscripciones, clases, pagos y seguimiento de miembros de forma automática. El agente IA motiva, recuerda y fideliza a tus clientes.',
    heroStats: [
      { valor: '90%', label: 'Menos no-shows en clases' },
      { valor: '3x', label: 'Más renovaciones' },
      { valor: '0', label: 'Pagos olvidados' },
    ],
    funciones: [
      { icon: '🏃', titulo: 'Inscripciones y planes', desc: 'El agente informa planes, precios y beneficios. El cliente se inscribe directamente por WhatsApp.' },
      { icon: '📅', titulo: 'Reserva de clases grupales', desc: 'Yoga, spinning, funcional, zumba — el cliente reserva su lugar con un mensaje.' },
      { icon: '💳', titulo: 'Recordatorios de pago', desc: '"Hola Juan, tu membresía vence en 3 días. ¿Renovamos?" — Reduce mora y abandono.' },
      { icon: '📊', titulo: 'Seguimiento de progreso', desc: 'Registra medidas, peso y metas. El agente hace seguimiento mensual y motiva.' },
      { icon: '🎯', titulo: 'Programas personalizados', desc: 'El agente comparte rutinas y planes nutricionales según el objetivo del miembro.' },
      { icon: '🏆', titulo: 'Gamificación y fidelización', desc: 'Medallas virtuales, rachas de asistencia y retos mensuales que mantienen a los miembros comprometidos.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, quiero inscribirme al gimnasio ¿qué planes tienen?' },
      { rol: 'agente', texto: '¡Hola! Bienvenido a PowerGym 💪 Tenemos estos planes:\n\n🥇 Mensual: 49€ - Acceso ilimitado\n🥈 Trimestral: 129€ - Ahorras 18€\n🥉 Semestral: 229€ - Ahorras 65€\n\nTodos incluyen pesas, cardio, clases grupales y asesoría inicial. ¿Cuál te interesa?' },
      { rol: 'cliente', texto: 'El mensual, ¿puedo empezar hoy?' },
      { rol: 'agente', texto: '¡Claro que sí! 🎉 Para activar tu membresía necesito:\n\n1️⃣ Tu nombre completo\n2️⃣ Foto del DNI o NIE\n3️⃣ Pago de 49€ (Bizum: 6XX-XXX-XXX)\n\nUna vez confirmes el pago, tienes acceso inmediato. ¿Tienes algún objetivo específico? 🏋️' },
    ],
    casos: [
      { nombre: 'PowerGym — Madrid', resultado: 'Aumentó retención de miembros del 45% al 78%' },
      { nombre: 'FitCenter — Barcelona', resultado: 'Automatizó cobros y redujo mora al 5%' },
      { nombre: 'CrossFit Valencia', resultado: 'Llenó clases al 100% con sistema de reservas IA' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'pro',
  },

  salon: {
    slug: 'salon',
    nombre: 'Salón de Belleza',
    emoji: '✂️',
    img: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#EC4899',
    colorBg: 'rgba(236,72,153,0.08)',
    colorBorder: 'rgba(236,72,153,0.2)',
    tagline: 'Tu agenda llena, tú enfocada en crear',
    descripcion: 'Olvídate de responder mensajes todo el día. Tu agente IA gestiona reservas, confirma citas, recuerda a los clientes y fideliza tu base con mensajes personalizados.',
    heroStats: [
      { valor: '4h', label: 'Ahorradas por día' },
      { valor: '95%', label: 'Tasa de confirmación' },
      { valor: '2x', label: 'Más reseñas Google' },
    ],
    funciones: [
      { icon: '📅', titulo: 'Reservas 24/7 por WhatsApp', desc: 'Tus clientes reservan a cualquier hora. El agente conoce tu agenda y nunca doble-agenda.' },
      { icon: '💆', titulo: 'Catálogo de servicios con precios', desc: 'El agente informa precios, duración y disponibilidad: corte, color, keratina, manicure, masajes.' },
      { icon: '🔔', titulo: 'Recordatorios automáticos', desc: 'WhatsApp automático 24h y 1h antes de la cita. Reduce las no-shows hasta un 70%.' },
      { icon: '🎂', titulo: 'Fidelización de clientes', desc: 'El sistema recuerda cumpleaños y envía descuentos especiales automáticamente.' },
      { icon: '📸', titulo: 'Portafolio digital', desc: 'Integra tu Instagram al agente para que los clientes vean tu trabajo antes de reservar.' },
      { icon: '💳', titulo: 'Gestión de pagos', desc: 'Informa métodos de pago, genera links de pago y registra transacciones en tu CRM.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Buenas, ¿cuánto vale el balayage?' },
      { rol: 'agente', texto: '¡Hola! El balayage tiene un valor desde 120€ dependiendo del largo y el efecto. ⏱️ Dura aproximadamente 3 horas. ¿Te gustaría ver ejemplos de nuestro trabajo?' },
      { rol: 'cliente', texto: 'Sí por favor, y también quiero saber disponibilidad para el sábado' },
      { rol: 'agente', texto: 'Aquí te dejo nuestro Instagram con trabajos recientes 👉 @salon_belle\n\nPara el sábado tenemos: 9:00am, 11:00am y 1:00pm disponibles. ¿Cuál te queda mejor? 💇‍♀️' },
      { rol: 'cliente', texto: '11am porfa, soy Patricia' },
      { rol: 'agente', texto: '✅ ¡Patricia, tu cita de balayage está confirmada para el sábado a las 11am! Te recuerdo el viernes. ¿Tienes alguna pregunta sobre el cuidado previo?' },
    ],
    casos: [
      { nombre: 'Studio Glam — Madrid', resultado: 'Llena el 100% de la agenda cada semana sin esfuerzo' },
      { nombre: 'Salón Belle — Valencia', resultado: 'Aumentó ventas de tratamientos premium en 60%' },
      { nombre: 'Peluquería Vogue — Barcelona', resultado: 'Eliminó por completo las citas no atendidas' },
    ],
    planes: ['Starter', 'Pro'],
    planRecomendado: 'starter',
  },

  salud: {
    slug: 'salud',
    nombre: 'Salud & Clínicas',
    emoji: '🏥',
    img: 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=120&h=120&fit=crop&crop=center&q=90',
    color: '#14B8A6',
    colorBg: 'rgba(20,184,166,0.08)',
    colorBorder: 'rgba(20,184,166,0.2)',
    tagline: 'Atención médica eficiente y sin esperas',
    descripcion: 'Agenda médica automatizada, recordatorios de citas, pre-triage inteligente e historial del paciente. Tus médicos se enfocan en la consulta, no en la administración.',
    heroStats: [
      { valor: '60%', label: 'Menos inasistencias' },
      { valor: '5 seg', label: 'Agenda una cita' },
      { valor: '100%', label: 'Citas confirmadas' },
    ],
    funciones: [
      { icon: '👨‍⚕️', titulo: 'Agenda médica inteligente', desc: 'El paciente agenda con el especialista que necesita, en el horario disponible, sin llamar ni esperar.' },
      { icon: '🩺', titulo: 'Pre-triage por chat', desc: 'El agente hace preguntas básicas antes de la cita: síntomas, duración, medicamentos actuales.' },
      { icon: '📋', titulo: 'Historial del paciente', desc: 'Registra visitas anteriores, diagnósticos, medicamentos y alergias para respuestas más precisas.' },
      { icon: '🔔', titulo: 'Recordatorios de citas y medicamentos', desc: 'Recordatorio 24h y 2h antes de la cita. También puede recordar toma de medicamentos.' },
      { icon: '📄', titulo: 'Entrega de resultados', desc: 'Notifica cuando los resultados están listos y los envía por WhatsApp de forma segura.' },
      { icon: '🏥', titulo: 'Información de servicios y tarifas', desc: 'Consultas, especialidades, precios, convenios con aseguradoras. El agente responde todo.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Buenas, necesito cita con médico general' },
      { rol: 'agente', texto: '¡Hola! Con gusto te ayudo a agendar tu cita 🏥\n\nPara orientarte mejor: ¿cuál es el motivo de consulta? (síntoma principal)' },
      { rol: 'cliente', texto: 'Llevo 3 días con dolor de garganta y fiebre' },
      { rol: 'agente', texto: 'Entendido. Para mañana tenemos disponible con:\n\n👨‍⚕️ Dr. Ramírez: 8:00am, 10:00am, 3:00pm\n👩‍⚕️ Dra. Torres: 9:00am, 11:30am, 4:00pm\n\nConsulta general: 45€. ¿Cuál médico y horario prefieres?' },
      { rol: 'cliente', texto: 'Con la Dra Torres a las 9am' },
      { rol: 'agente', texto: '✅ ¡Cita confirmada! Dra. Torres, mañana 9:00am.\n\nRecuerda traer:\n📋 DNI o tarjeta sanitaria\n💊 Lista de medicamentos actuales\n\nTe enviaré un recordatorio mañana a las 7am. ¿Tienes alguna alergia conocida?' },
    ],
    casos: [
      { nombre: 'Clínica Bienestar — Madrid', resultado: 'Redujo inasistencias del 35% al 8%' },
      { nombre: 'Consultorio Dr. Herrera — Bilbao', resultado: 'Triplicó la capacidad de agenda sin contratar más personal' },
      { nombre: 'Centro Médico Levante — Valencia', resultado: 'Satisfacción del paciente subió de 7.2 a 9.4/10' },
    ],
    planes: ['Pro', 'Enterprise'],
    planRecomendado: 'pro',
  },
};

export const SLUGS_VALIDOS = Object.keys(INDUSTRIAS_DETALLE);
