// lib/industriasData.js
export const INDUSTRIAS_DETALLE = {
  taller: {
    slug: 'taller',
    nombre: 'Talleres & Mecánica',
    emoji: '🔧',
    color: '#FF6B6B',
    colorBg: 'rgba(255,107,107,0.08)',
    colorBorder: 'rgba(255,107,107,0.2)',
    tagline: 'Tu taller en piloto automático',
    descripcion: 'Automatiza citas, presupuestos y seguimiento de vehículos. Tu agente IA atiende clientes por WhatsApp las 24 horas, agenda revisiones y envía recordatorios automáticos.',
    heroStats: [
      { valor: '3x', label: 'Más citas agendadas' },
      { valor: '80%', label: 'Menos llamadas perdidas' },
      { valor: '24/7', label: 'Atención continua' },
    ],
    funciones: [
      { icon: '📅', titulo: 'Agendamiento automático de citas', desc: 'Tu agente recibe solicitudes por WhatsApp, consulta disponibilidad y agenda la cita sin que intervengas. El cliente recibe confirmación inmediata.' },
      { icon: '🚗', titulo: 'Historial de vehículos', desc: 'Registra automáticamente cada vehículo: placa, modelo, año, servicios realizados y próximo mantenimiento recomendado.' },
      { icon: '💰', titulo: 'Presupuestos automáticos', desc: 'El agente genera cotizaciones preliminares basadas en la descripción del problema. Envía al cliente y espera aprobación.' },
      { icon: '🔔', titulo: 'Recordatorios de mantenimiento', desc: 'Sistema de recordatorios automáticos: "Tu vehículo necesita revisión de aceite en 500 km". Fideliza clientes sin esfuerzo.' },
      { icon: '💬', titulo: 'Seguimiento de reparaciones', desc: 'Notifica al cliente el estado de su vehículo: recibido, en diagnóstico, en reparación, listo para recoger.' },
      { icon: '⭐', titulo: 'Reseñas automáticas', desc: 'Al terminar el servicio, el agente pide reseña en Google y guarda feedback en tu CRM para mejorar continuamente.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, necesito cambio de aceite para mi Mazda 3 2020' },
      { rol: 'agente', texto: '¡Hola! Con gusto te ayudo 👋 El cambio de aceite para tu Mazda 3 2020 tiene un valor aproximado de $80.000 COP e incluye filtro. ¿Te gustaría agendar una cita?' },
      { rol: 'cliente', texto: 'Sí, ¿tienen disponibilidad mañana?' },
      { rol: 'agente', texto: 'Claro, mañana tenemos disponible: 8:00am, 10:30am y 2:00pm. ¿Cuál prefieres? 😊' },
      { rol: 'cliente', texto: '10:30 am perfecto' },
      { rol: 'agente', texto: '✅ ¡Listo! Cita confirmada para mañana a las 10:30am. Te enviaré un recordatorio 1 hora antes. ¿Cuál es tu placa para registrar el vehículo?' },
    ],
    casos: [
      { nombre: 'AutoCenter Medellín', resultado: 'Pasó de 8 a 23 citas semanales en el primer mes' },
      { nombre: 'Taller Don Pedro', resultado: 'Redujo llamadas perdidas en un 85%' },
      { nombre: 'Mecánica Express Cali', resultado: 'Recuperó 40 clientes inactivos con recordatorios IA' },
    ],
    planes: ['Emprendedor', 'Profesional'],
    planRecomendado: 'profesional',
  },

  peluqueria: {
    slug: 'peluqueria',
    nombre: 'Peluquerías & Spa',
    emoji: '✂️',
    color: '#EC4899',
    colorBg: 'rgba(236,72,153,0.08)',
    colorBorder: 'rgba(236,72,153,0.2)',
    tagline: 'Tu agenda llena, tú enfocada en crear',
    descripcion: 'Olvídate de responder mensajes todo el día. Tu agente IA gestiona reservas, confirma citas, recuerda a los clientes y fideliza tu base con mensajes personalizados.',
    heroStats: [
      { valor: '4h', label: 'Ahorradas por día' },
      { valor: '95%', label: 'Tasa de confirmación' },
      { valor: '2x', label: 'Más reseñas Google' },
    ],
    funciones: [
      { icon: '📅', titulo: 'Reservas 24/7 por WhatsApp', desc: 'Tus clientes reservan a cualquier hora, incluso de madrugada. El agente conoce tu agenda y nunca doble-agenda.' },
      { icon: '💆', titulo: 'Catálogo de servicios con precios', desc: 'El agente informa precios, duración y disponibilidad de cada servicio: corte, color, keratina, manicure, masajes.' },
      { icon: '🔔', titulo: 'Recordatorios automáticos', desc: 'WhatsApp automático 24h y 1h antes de la cita. Reduce las no-shows hasta un 70%.' },
      { icon: '🎂', titulo: 'Fidelización de clientes', desc: 'El sistema recuerda cumpleaños y envía descuentos especiales automáticamente a tus clientes frecuentes.' },
      { icon: '📸', titulo: 'Portafolio digital', desc: 'Integra tu Instagram al agente para que los clientes vean tu trabajo antes de reservar.' },
      { icon: '💳', titulo: 'Gestión de pagos', desc: 'Informa métodos de pago, genera links de pago con Wompi y registra transacciones en tu CRM.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Buenas, ¿cuánto vale el balayage?' },
      { rol: 'agente', texto: '¡Hola! El balayage tiene un valor desde $180.000 COP dependiendo del largo y el efecto. ⏱️ Dura aproximadamente 3 horas. ¿Te gustaría ver ejemplos de nuestro trabajo?' },
      { rol: 'cliente', texto: 'Sí por favor, y también quiero saber disponibilidad para el sábado' },
      { rol: 'agente', texto: 'Aquí te dejo nuestro Instagram con trabajos recientes 👉 @estudio_elegance\n\nPara el sábado tenemos: 9:00am, 11:00am y 1:00pm disponibles. ¿Cuál te queda mejor? 💇‍♀️' },
      { rol: 'cliente', texto: '11am porfa, soy Patricia' },
      { rol: 'agente', texto: '✅ ¡Patricia, tu cita de balayage está confirmada para el sábado a las 11am! Te recuerdo el viernes. ¿Tienes alguna pregunta sobre el cuidado previo?' },
    ],
    casos: [
      { nombre: 'Studio Glam Bogotá', resultado: 'Llena el 100% de la agenda cada semana sin esfuerzo' },
      { nombre: 'Spa Natura Cali', resultado: 'Aumentó ventas de tratamientos premium en 60%' },
      { nombre: 'Peluquería Vogue', resultado: 'Eliminó por completo las citas no atendidas' },
    ],
    planes: ['Emprendedor', 'Profesional'],
    planRecomendado: 'emprendedor',
  },

  inmobiliaria: {
    slug: 'inmobiliaria',
    nombre: 'Inmobiliarias',
    emoji: '🏠',
    color: '#3B82F6',
    colorBg: 'rgba(59,130,246,0.08)',
    colorBorder: 'rgba(59,130,246,0.2)',
    tagline: 'Tu agente inmobiliario que nunca descansa',
    descripcion: 'Filtra prospectos automáticamente, muestra propiedades, responde preguntas técnicas y agenda visitas. Tus asesores solo atienden clientes listos para comprar o arrendar.',
    heroStats: [
      { valor: '5x', label: 'Más leads calificados' },
      { valor: '60%', label: 'Menos tiempo en filtrado' },
      { valor: '24/7', label: 'Atención de prospectos' },
    ],
    funciones: [
      { icon: '🏘️', titulo: 'Catálogo de propiedades inteligente', desc: 'El agente pregunta: presupuesto, zona, habitaciones y tipo. Filtra y muestra solo las propiedades que encajan con el prospecto.' },
      { icon: '📋', titulo: 'Calificación automática de leads', desc: 'Clasifica prospectos por nivel de urgencia, capacidad económica e intención de compra. Tu equipo enfoca esfuerzos donde vale.' },
      { icon: '📅', titulo: 'Agenda de visitas automática', desc: 'El agente coordina visitas, confirma al prospecto y al asesor, y envía la dirección y detalles automáticamente.' },
      { icon: '📊', titulo: 'Seguimiento post-visita', desc: 'Después de cada visita, el agente hace seguimiento: ¿qué te pareció? ¿tienes preguntas? ¿quieres hacer oferta?' },
      { icon: '📄', titulo: 'Información técnica de inmuebles', desc: 'Estrato, área, precio, administración, parqueadero, piso, antigüedad. El agente responde todo sin que el asesor intervenga.' },
      { icon: '🔔', titulo: 'Alertas de nuevas propiedades', desc: 'Notifica automáticamente a prospectos registrados cuando entra una propiedad que coincide con su búsqueda.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, busco apartamento en arriendo en el sur de Cali, máximo 1.5 millones' },
      { rol: 'agente', texto: '¡Hola! Perfecto, tengo varias opciones en el sur de Cali dentro de tu presupuesto 🏠\n\n¿Cuántas habitaciones necesitas y en qué barrio prefieres?' },
      { rol: 'cliente', texto: '2 habitaciones, de preferencia en Ciudad Jardín o El Ingenio' },
      { rol: 'agente', texto: 'Excelente elección! Tengo 3 opciones disponibles ahora mismo:\n\n🏠 Apto Ciudad Jardín - 2 hab, 2 baños, $1.400.000/mes, piso 4\n🏠 Apto El Ingenio - 2 hab, 1 baño, $1.250.000/mes, parqueadero\n🏠 Apto Sur - 2 hab, 2 baños, $1.480.000/mes, vista despejada\n\n¿Cuál te llama más la atención para agendar visita?' },
      { rol: 'cliente', texto: 'El de Ciudad Jardín, ¿podemos ver el fin de semana?' },
      { rol: 'agente', texto: '✅ ¡Claro! El sábado tenemos disponible 10am o 3pm para la visita. ¿Cuál prefieres? Te confirmo con el asesor de inmediato 📅' },
    ],
    casos: [
      { nombre: 'Inversión Finca Raíz Bogotá', resultado: 'Triplicó visitas agendadas en el primer mes' },
      { nombre: 'Propiedades del Valle', resultado: 'Redujo tiempo de calificación de leads de 2 días a 2 minutos' },
      { nombre: 'Inmobiliaria Pacífico', resultado: 'Vendió 8 inmuebles en 45 días con leads del agente IA' },
    ],
    planes: ['Profesional', 'Agencia'],
    planRecomendado: 'profesional',
  },

  restaurante: {
    slug: 'restaurante',
    nombre: 'Restaurantes & Comidas',
    emoji: '🍕',
    color: '#EAB308',
    colorBg: 'rgba(234,179,8,0.08)',
    colorBorder: 'rgba(234,179,8,0.2)',
    tagline: 'Más pedidos, menos llamadas',
    descripcion: 'Tu restaurante toma pedidos por WhatsApp automáticamente, gestiona reservas de mesas, informa el menú del día y hace seguimiento de domicilios sin que muevas un dedo.',
    heroStats: [
      { valor: '35%', label: 'Más pedidos por WhatsApp' },
      { valor: '0', label: 'Llamadas perdidas' },
      { valor: '2 seg', label: 'Tiempo de respuesta' },
    ],
    funciones: [
      { icon: '🍽️', titulo: 'Toma de pedidos por WhatsApp', desc: 'El agente muestra el menú, toma el pedido, confirma la dirección y el método de pago. Todo sin intervención humana.' },
      { icon: '📋', titulo: 'Menú digital interactivo', desc: 'Menú siempre actualizado con fotos, precios, ingredientes y alérgenos. Se actualiza en minutos desde el panel.' },
      { icon: '🪑', titulo: 'Reservas de mesas', desc: 'Gestiona reservas de mesas para grupos, eventos especiales y fechas importantes con confirmación automática.' },
      { icon: '🛵', titulo: 'Seguimiento de domicilios', desc: 'Notifica al cliente cuando su pedido está en preparación, listo y en camino. Reduce llamadas de "¿dónde está mi pedido?"' },
      { icon: '⏰', titulo: 'Tiempo de espera en tiempo real', desc: 'El agente informa tiempos de espera estimados según el volumen actual de pedidos.' },
      { icon: '🎉', titulo: 'Promociones automáticas', desc: 'Envía promos del día, combos especiales y descuentos a clientes frecuentes automáticamente.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola quiero pedir domicilio' },
      { rol: 'agente', texto: '¡Hola! 🍕 Bienvenido a Pizza Express. ¿Ya conoces nuestro menú o quieres verlo?' },
      { rol: 'cliente', texto: 'Sí, una pizza familiar de pepperoni y una gaseosa' },
      { rol: 'agente', texto: '¡Perfecto! Tu pedido:\n🍕 Pizza familiar pepperoni - $42.000\n🥤 Gaseosa 1.5L - $6.000\n\nTotal: $48.000\n\n¿Cuál es tu dirección de entrega? 📍' },
      { rol: 'cliente', texto: 'Calle 15 # 28-40, apto 302' },
      { rol: 'agente', texto: '✅ Pedido confirmado! Tiempo estimado: 35-40 minutos.\n\n¿Pagas en efectivo o por Nequi/Daviplata? 💳' },
    ],
    casos: [
      { nombre: 'Pizza Express Cali', resultado: 'Aumentó pedidos WhatsApp de 20 a 85 por día' },
      { nombre: 'Restaurante La Cazuela', resultado: 'Eliminó el 90% de llamadas telefónicas en hora pico' },
      { nombre: 'Sushi Delivery Bogotá', resultado: 'Incrementó ticket promedio 25% con sugerencias IA' },
    ],
    planes: ['Emprendedor', 'Profesional'],
    planRecomendado: 'emprendedor',
  },

  tienda: {
    slug: 'tienda',
    nombre: 'Tiendas & Retail',
    emoji: '🛒',
    color: '#10B981',
    colorBg: 'rgba(16,185,129,0.08)',
    colorBorder: 'rgba(16,185,129,0.2)',
    tagline: 'Tu vendedor digital que nunca cierra',
    descripcion: 'Tu tienda vende las 24 horas sin contratar más personal. El agente IA muestra productos, verifica disponibilidad, procesa pedidos y hace seguimiento postventa automáticamente.',
    heroStats: [
      { valor: '24/7', label: 'Ventas activas' },
      { valor: '40%', label: 'Más conversiones' },
      { valor: '3x', label: 'Más clientes atendidos' },
    ],
    funciones: [
      { icon: '🛍️', titulo: 'Catálogo digital con búsqueda inteligente', desc: 'El cliente describe lo que busca y el agente encuentra el producto exacto entre todo tu inventario.' },
      { icon: '📦', titulo: 'Verificación de inventario en tiempo real', desc: 'El agente consulta stock antes de confirmar. Si no hay, ofrece alternativas similares automáticamente.' },
      { icon: '💰', titulo: 'Asistente de ventas con upselling', desc: 'Sugiere productos complementarios: "Con esa impresora también llevas cartuchos de larga duración".' },
      { icon: '🚚', titulo: 'Gestión de pedidos y entregas', desc: 'Registra pedidos, coordina envíos, genera guías y notifica al cliente el estado de su compra.' },
      { icon: '🔄', titulo: 'Postventa automático', desc: 'Seguimiento después de la compra: ¿llegó bien? ¿necesitas factura? ¿quieres dejar una reseña?' },
      { icon: '📊', titulo: 'Reportes de productos más vendidos', desc: 'Tu panel muestra qué productos se consultan más, cuáles generan más ventas y cuáles necesitan restock.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Buenas, ¿tienen cartuchos para impresora HP Deskjet 2775?' },
      { rol: 'agente', texto: '¡Hola! Sí, tenemos cartuchos para tu HP Deskjet 2775 🖨️\n\n✅ Cartucho negro HP 664 - $28.000 (en stock)\n✅ Cartucho color HP 664 - $35.000 (en stock)\n✅ Pack combo negro+color - $58.000 (ahorra $5.000)\n\n¿Cuál prefieres?' },
      { rol: 'cliente', texto: 'El combo, ¿hacen domicilio?' },
      { rol: 'agente', texto: '¡Claro! Domicilio disponible. ¿Cuál es tu ubicación para calcular el costo de envío? 📍\n\nTambién puedes pasar a recogerte hoy, estamos abiertos hasta las 7pm.' },
    ],
    casos: [
      { nombre: 'Papelería Central Cali', resultado: 'Atendió 3x más clientes con el mismo personal' },
      { nombre: 'Ferretería Los Andes', resultado: 'Ventas online crecieron 150% en 60 días' },
      { nombre: 'Distribuidora TecnoPlus', resultado: 'Redujo tiempo de atención por cliente de 8 min a 90 seg' },
    ],
    planes: ['Emprendedor', 'Profesional'],
    planRecomendado: 'profesional',
  },

  papeleria: {
    slug: 'papeleria',
    nombre: 'Papelerías & Servicios',
    emoji: '📋',
    color: '#8B5CF6',
    colorBg: 'rgba(139,92,246,0.08)',
    colorBorder: 'rgba(139,92,246,0.2)',
    tagline: 'Cotizaciones instantáneas, clientes satisfechos',
    descripcion: 'Genera cotizaciones automáticas de impresión, diseño y servicios en segundos. Tu agente IA atiende solicitudes, hace seguimiento de pedidos y fideliza clientes recurrentes.',
    heroStats: [
      { valor: '10 seg', label: 'Cotización automática' },
      { valor: '70%', label: 'Menos tiempo en atención' },
      { valor: '2x', label: 'Más pedidos por WhatsApp' },
    ],
    funciones: [
      { icon: '💰', titulo: 'Cotizaciones automáticas de impresión', desc: 'El cliente indica qué necesita (hojas, tamaño, color, cantidad) y el agente calcula y envía la cotización en segundos.' },
      { icon: '🎨', titulo: 'Solicitud de diseño gráfico', desc: 'Recibe briefings de diseño, confirma el encargo, hace seguimiento y entrega el archivo cuando está listo.' },
      { icon: '📂', titulo: 'Gestión de pedidos', desc: 'Registra cada pedido, asigna número de seguimiento y notifica al cliente cuando está listo para recoger o enviar.' },
      { icon: '🖨️', titulo: 'Catálogo de servicios con precios', desc: 'Impresión, plastificado, espiral, empaste, copias, ploteos, tarjetas de presentación. Todo con precios y tiempos.' },
      { icon: '🔔', titulo: 'Avisos de pedido listo', desc: '"Tu pedido de 200 volantes ya está listo para recoger en nuestra sede" — automático, sin que hagas nada.' },
      { icon: '📊', titulo: 'Clientes frecuentes con descuentos', desc: 'El sistema identifica clientes recurrentes y aplica descuentos automáticos según su historial de compras.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Buenas, necesito 500 volantes a color tamaño carta para una evento' },
      { rol: 'agente', texto: '¡Hola! Para 500 volantes a color tamaño carta:\n\n📄 Papel bond 90g: $85.000\n📄 Papel couché brillante: $120.000\n📄 Papel couché mate: $115.000\n\n⏱️ Tiempo de entrega: 2-3 horas\n\n¿Tienes el diseño listo o necesitas que lo hagamos? 🎨' },
      { rol: 'cliente', texto: 'Ya tengo el diseño, lo envío ahora. ¿Cuándo estarían listos?' },
      { rol: 'agente', texto: '¡Perfecto! Envía el archivo en PDF o AI a este mismo chat. Si los pides antes de las 11am, los tienes listos hoy en la tarde. ¿Confirmas el pedido en papel couché brillante? 🖨️' },
    ],
    casos: [
      { nombre: 'Copy Rápido Medellín', resultado: 'Cotizaciones automáticas ahorraron 4 horas diarias' },
      { nombre: 'Papelería Universitaria', resultado: 'Atendió 5x más clientes en temporada escolar' },
      { nombre: 'Servicios Gráficos Sur', resultado: 'Cero pedidos perdidos por falta de atención' },
    ],
    planes: ['Emprendedor', 'Profesional'],
    planRecomendado: 'emprendedor',
  },

  gimnasio: {
    slug: 'gimnasio',
    nombre: 'Gimnasios & Fitness',
    emoji: '🏋️',
    color: '#F97316',
    colorBg: 'rgba(249,115,22,0.08)',
    colorBorder: 'rgba(249,115,22,0.2)',
    tagline: 'Más miembros, menos gestión',
    descripcion: 'Tu gimnasio gestiona inscripciones, clases, pagos y seguimiento de miembros de forma automática. El agente IA motiva, recuerda y fideliza a tus clientes.',
    heroStats: [
      { valor: '90%', label: 'Menos no-shows en clases' },
      { valor: '3x', label: 'Más renovaciones' },
      { valor: '0', label: 'Pagos olvidados' },
    ],
    funciones: [
      { icon: '🏃', titulo: 'Inscripciones y planes', desc: 'El agente informa planes, precios y beneficios. El cliente se inscribe directamente por WhatsApp sin ir al gimnasio.' },
      { icon: '📅', titulo: 'Reserva de clases grupales', desc: 'Yoga, spinning, funcional, zumba — el cliente reserva su lugar en la clase con un mensaje. Cupos limitados gestionados automáticamente.' },
      { icon: '💳', titulo: 'Recordatorios de pago', desc: '"Hola Juan, tu membresía vence en 3 días. ¿Renovamos?" — Reduce mora y abandono con recordatorios amigables.' },
      { icon: '📊', titulo: 'Seguimiento de progreso', desc: 'Registra medidas, peso y metas de cada miembro. El agente hace seguimiento mensual y motiva con mensajes personalizados.' },
      { icon: '🎯', titulo: 'Programas personalizados', desc: 'El agente comparte rutinas y planes nutricionales según el objetivo del miembro: pérdida de peso, masa muscular, resistencia.' },
      { icon: '🏆', titulo: 'Gamificación y fidelización', desc: 'Medallas virtuales, rachas de asistencia y retos mensuales que mantienen a los miembros comprometidos.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Hola, quiero inscribirme al gimnasio ¿qué planes tienen?' },
      { rol: 'agente', texto: '¡Hola! Bienvenido a PowerGym 💪 Tenemos estos planes:\n\n🥇 Mensual: $120.000 - Acceso ilimitado\n🥈 Trimestral: $320.000 - Ahorra $40.000\n🥉 Semestral: $550.000 - Ahorra $170.000\n\nTodos incluyen: pesas, cardio, clases grupales y asesoría inicial. ¿Cuál te interesa?' },
      { rol: 'cliente', texto: 'El mensual, ¿puedo empezar hoy?' },
      { rol: 'agente', texto: '¡Claro que sí! 🎉 Para activar tu membresía necesito:\n\n1️⃣ Tu nombre completo\n2️⃣ Foto del documento de identidad\n3️⃣ Pago de $120.000 (Nequi: 300-xxx-xxxx)\n\nUna vez confirmes el pago, tienes acceso inmediato. ¿Tienes algún objetivo específico para tu entrenamiento? 🏋️' },
    ],
    casos: [
      { nombre: 'PowerGym Cali', resultado: 'Aumentó retención de miembros del 45% al 78%' },
      { nombre: 'FitCenter Bogotá', resultado: 'Automatizó cobros y redujo mora al 5%' },
      { nombre: 'CrossFit Pacífico', resultado: 'Llenó clases al 100% con sistema de reservas IA' },
    ],
    planes: ['Emprendedor', 'Profesional'],
    planRecomendado: 'profesional',
  },

  salud: {
    slug: 'salud',
    nombre: 'Salud & Clínicas',
    emoji: '🏥',
    color: '#14B8A6',
    colorBg: 'rgba(20,184,166,0.08)',
    colorBorder: 'rgba(20,184,166,0.2)',
    tagline: 'Atención médica eficiente y sin filas',
    descripcion: 'Agenda médica automatizada, recordatorios de citas, pre-triage inteligente e historial del paciente. Tus médicos se enfocan en la consulta, no en la administración.',
    heroStats: [
      { valor: '60%', label: 'Menos inasistencias' },
      { valor: '5 seg', label: 'Agenda una cita' },
      { valor: '100%', label: 'Citas confirmadas' },
    ],
    funciones: [
      { icon: '👨‍⚕️', titulo: 'Agenda médica inteligente', desc: 'El paciente agenda con el especialista que necesita, en el horario disponible, sin llamar ni esperar en fila.' },
      { icon: '🩺', titulo: 'Pre-triage por chat', desc: 'El agente hace preguntas básicas antes de la cita: síntomas, duración, medicamentos actuales. El médico llega preparado.' },
      { icon: '📋', titulo: 'Historial del paciente', desc: 'Registra visitas anteriores, diagnósticos, medicamentos y alergias. El agente usa esta info para respuestas más precisas.' },
      { icon: '🔔', titulo: 'Recordatorios de citas y medicamentos', desc: 'Recordatorio 24h y 2h antes de la cita. También puede recordar toma de medicamentos según prescripción.' },
      { icon: '📄', titulo: 'Entrega de resultados', desc: 'Notifica cuando los resultados de exámenes están listos y los envía digitalmente por WhatsApp de forma segura.' },
      { icon: '🏥', titulo: 'Información de servicios y tarifas', desc: 'Consultas, especialidades, precios, convenios con seguros. El agente responde todo sin saturar la recepción.' },
    ],
    flujoChat: [
      { rol: 'cliente', texto: 'Buenas, necesito cita con médico general' },
      { rol: 'agente', texto: '¡Hola! Con gusto te ayudo a agendar tu cita 🏥\n\nPara orientarte mejor: ¿cuál es el motivo de consulta? (síntoma principal)' },
      { rol: 'cliente', texto: 'Llevo 3 días con dolor de garganta y fiebre' },
      { rol: 'agente', texto: 'Entendido. Para mañana tenemos disponible con:\n\n👨‍⚕️ Dr. Ramírez: 8:00am, 10:00am, 3:00pm\n👩‍⚕️ Dra. Torres: 9:00am, 11:30am, 4:00pm\n\nTarifas: Consulta general $45.000. ¿Cuál médico y horario prefieres?' },
      { rol: 'cliente', texto: 'Con la Dra Torres a las 9am' },
      { rol: 'agente', texto: '✅ ¡Cita confirmada! Dra. Torres, mañana 9:00am.\n\nTe recuerdo que debes traer:\n📋 Documento de identidad\n💊 Lista de medicamentos actuales\n\nTe enviaré un recordatorio mañana a las 7am. ¿Tienes alguna alergia conocida a medicamentos?' },
    ],
    casos: [
      { nombre: 'Clínica Bienestar Cali', resultado: 'Redujo inasistencias del 35% al 8%' },
      { nombre: 'Consultorio Dr. Herrera', resultado: 'Triplicó la capacidad de agenda sin contratar más personal' },
      { nombre: 'Centro Médico Pacífico', resultado: 'Satisfacción del paciente subió de 7.2 a 9.4/10' },
    ],
    planes: ['Profesional', 'Agencia'],
    planRecomendado: 'profesional',
  },
};

export const SLUGS_VALIDOS = Object.keys(INDUSTRIAS_DETALLE);
